FROM node:8.6

# dumb-init acts as PID 1 and immediately spawns your command as a child process, taking care to properly handle and forward signals as they are received.
RUN wget https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64.deb
RUN dpkg -i dumb-init_*.deb

# Set Home env, this is where our app is going to live
ENV HOME=/usr/app

# Change directory so that our commands run inside this new directory
WORKDIR $HOME/src

# DISABLED
# User for any RUN, CMD and ENTRYPOINT command
# Warning: When the user does doesn’t have a primary group then the image (or the next instructions) will be run with the root group.
# USER app

# Copy the dependencies description and set permissions to app
COPY package.json .
COPY package-lock.json .

# Install and Cache npm packages
RUN npm install

# Expose the port the app runs in
EXPOSE 3000

ENTRYPOINT ["/usr/bin/dumb-init", "--", "./docker-entrypoint-dev.sh"]
